# -*- coding: utf-8 -*-
"""Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f73d__ehA2Jo1xRn5ISBrH2bbhIQWY-d

while loop
"""

#1 Print all even numbers from 1 to 100 and count them
count = 1
even_count = 0

while count <= 100:
    if count % 2 == 0:
        print(count)
        even_count += 1
    count += 1

print("Total even numbers:", even_count)

#2 Calculate the sum of all numbers between 30 and 60 (inclusive)
i = 30
sum = 0
while i <= 60:
    sum += i
    i+= 1
print(sum)

#3 Find and print numbers from 1 to 100 that are divisible by 3 but not by 9
i = 1
while i <= 100:
    if i % 3 == 0 and i % 9 != 0:
        print(i)
    i += 1

#4 Count how many numbers between 1 and 50 are divisible by 4
i = 1
count = 0

while i <= 50:
    if i % 4 == 0:
        count += 1
    i += 1

print(count)

#5 Print the squares of all numbers from 1 to 20
i = 1
while i <= 20:
  print(i*2)
  i += 1

#6 Print all numbers from 1 to 50 in reverse order
i = 50
while i >= 1:
  print(i, end = " ")
  i -= 1

#7 Print all odd numbers between 10 and 30 and calculate their sum
i = 10
sum = 0
odd_number = 0
while i <= 30:
  if i % 2 != 0:
    print(i)
    sum += i
    odd_number += 1
  i+=1
print(sum)
print( odd_number)

#8 Find the sum of digits of a given number (e.g., 1234 → 1+2+3+4 = 10)
num = int(input("Enter a number: "))
sum = 0
while num > 0:
    digit = num % 10
    sum += digit
    num //= 10
print("Sum of digits:", sum)

#9 Count how many numbers between 1 and 100 are divisible by both 2 and 3
count = 0
i = 1

while i <= 100:
    if i % 2 == 0 and i % 3 == 0:
        count += 1
    i += 1

print(count)

#10 Print the multiplication table of a given number up to 10 (e.g., 5 × 1 to 5 × 10) using while loop
num = int(input("Enter a number: "))
i = 1

while i <= 10:
    print(f"{num} x {i} = {num * i}")
    i += 1

#11 Print numbers from 1 to 10 using a while loop.
i = 1
while i <= 100:
  print(i, end = " ")
  i += 1

#12 Print all even numbers from 1 to 50 using a while loop.
i = 1
while i <= 50:
  if i % 2 == 0:
       print(i)
  i+=1

#13 Print all odd numbers from 100 to 1 using a while loop.
i = 100
while i >= 1:
  if i % 2!= 0:
    print(i, end = " ")
  i -= 1

#14 Calculate the sum of numbers from 1 to 100 using a while loop.
i = 1
sum = 0
while i <= 100:
  sum += i
  i += 1
print(sum)

#15 Calculate the product of numbers from 1 to 10 using a while loop.
i = 1
product = 1
while i <= 10:
  product = product * i
  i += 1
print(product)

"""##### For loop

"""

#1 Print numbers from 1 to 10 using a for loop.
for i in range (1,11):
   print(i)

#2 Print all even numbers from 2 to 100 using a for loop.
for i in range(2,101):
  if i % 2 == 0:
    print(i, end= " ")

#3 Print all odd numbers between 1 and 50.
for i in range(1,51):
  if i % 3 == 0:
    print(i, end= " ")

#4 Print numbers from 50 to 1 in reverse order.
for i in range(50,0,-1):
  print(i, end= " ")

#5 Print the table of 5 using a for loop.
for i in range(5,51):
  if i % 5 == 0:
    print(i, end= " ")

#6 Print the square of numbers from 1 to 10
for i in range(1,11):
  print(i*i, end = " ")

#7 Print the cube of numbers from 1 to 10.
for i in range(1,11):
  print(i*i*i, end = " ")

#8 Print all numbers between 1 and 20 that are divisible by 3.
for i in range(1,21):
  if i % 3 == 0:
    print(i)

#9 Print the sum of numbers from 1 to 100 using a for loop.
sum = 0
for i in range(1,101):
  sum += i
print(sum)

#10 Print the product of numbers from 1 to 5 using a for loop.
product = 1
for i in range(1,6):
  product = product * i
print(product)

"""Nested for loop"""

# 1.*****
#   *****
#   *****
#   *****
#   *****

row = 5
for i in range(5):
  for j in range(1,6):
    print("*", end = "")
  print()

#2  11111
#   22222
#   33333
#   44444
#   55555
for i in range(1,6):
  for j in range(1,6):
     print(i,end = "")
  print()

# 3.12345
#   12345
#   12345
#   12345
#   12345

for i in range(1,6):
  for j in range(1,6):
    print(j,end = "")
  print()

# 4.55555
#   44444
#   33333
#   22222
#   11111

for i in range(5,0,-1):
  for j in range(5,0,-1):
    print(i,end = "")
  print()

# 5.54321
#   54321
#   54321
#   54321
#   54321

for i in range(5,0,-1):
  for j in range(5,0,-1):
    print(j,end = "")
  print()

# 6. *
#    **
#    ***
#    ****
#    *****

row = 5
for i in range(1,row+1):
  for j in range(i):
    print("*", end = "")
  print()

# 7. 1
#    22
#    333
#    4444
#    55555

row = 5
for i in range(1,row+1):
  for j in range(i):
    print(i, end = "")
  print()

# 8.AAAAA
#   BBBBB
#   CCCCC
#   DDDDD
#   EEEEE
row = 5
for i in range(1,row+1):
   for j in range(1,row+1):
     print(chr(64+i), end = "")
   print()

# 9.ABCDE
#   ABCDE
#   ABCDE
#   ABCDE
#   ABCDE

row = 5
for i in range(1,6):
  for j in range(1,6):
    print(chr(64+j), end = "")
  print()

# 10.EEEEE
#    DDDDD
#    CCCCC
#    BBBBB
#    AAAAA

for i in range(5,0,-1):
  for j in range(5,0,-1):
    print(chr(64+i), end = "")
  print()

# 11Flyod Triangle
# 1
# 2 3
# 4 5 6
# 7 8 9 10
row = 4
num = 1
for i in range(1,row+1):
    for j in range(i):
        print(num, end = " ")
        num += 1
    print()

# 24.    *
#       **
#      ***
#     ****
#    *****

row = 5
for i in range(1,row+1):
  for j in range(row-i):
     print(" ",end = "")
  for j in range(i):
     print("*",end = "")
  print()

